version: '3.9'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "333:333"

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "85:80"
    depends_on:
      - web