version: '3.9' # version de docker-compose

services: #declaracion de servicios para el contenedor    
  postgres:
    image: postgres
    ports:
      -5431:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database:/var/lib/postgresql/data
  django:
    build: .
    ports:
      -433:8000
    volumes:
      -.:/app
    depends_on:
      - postgres
  