version: '3.9'

services:
  django:
    build: .
    volumes:
      - .:/django-project
    ports:
      - "333:333"

  nginx:
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./nginx/conf.d:/etc/nginx/conf.d:rw
      - ./static:/django-project/static  # Ajusta según tu configuración de archivos estáticos
      - ./media:/django-project/media    # Ajusta según tu configuración de archivos multimedia
      - ./ssl:/etc/nginx/certs
    ports:
      - "80:85"
      - "8080:8080"
    depends_on:
      - django